language: go

sudo: false

matrix:
  include:
    - go: "1.7"
    - go: "1.9"
    - go: "1.11"
    - go: master

before_install:
  - go get github.com/mattn/goveralls

script:
  - $GOPATH/bin/goveralls -service=travis-ci
  - go build ./...
  - go test -v ./...
